name: Create Source Plugin PR
on:
  pull_request:
    types: [opened]
    branches:
      - develop
      - master
jobs:
  create_pr:
    runs-on: ubuntu-18.04
    steps:
      - uses: octokit/request-action@v2.x
        with:
          route: POST /repos/{owner}/{repo}/actions/workflows/{workflow}/dispatches
          owner: gatsbyjs
          repo: gatsby-source-wordpress-experimental
          workflow: wp-gatsby-pr.yml
          ref: master
          remoteref: $GITHUB_BASE_REF
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
