name: Create Source Plugin PR
on:
  pull_request:
    types: [opened]
    branches:
      - develop
      - master
    paths:
      - '**.php'
      - '!docs/**'
jobs:
  create_pr:
    runs-on: ubuntu-18.04
    steps:
      - run: ./bin/create-source-plugin-pr.sh
