name: Create Source Plugin PR
on:
  pull_request:
    types: [opened]
    branches:
      - develop
      - master
jobs:
  create_pr:
    runs-on: ubuntu-18.04
    steps:
      - uses: octokit/request-action@v2.x
        id: create_source_plugin_pr
        with:
          route: POST /{owner}/{repo}/actions/workflows/.github/workflows/wp-gatsby-pr.yml/dispatches
          owner: gatsbjys
          repo: gatsby-source-wordpress-experimental
          ref: master
          remoteref: $GITHUB_REF
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
