name: Run Source Plugin PR CI for every WP Gatsby PR push
on: [push]
jobs:
  run_ci:
    runs-on: ubuntu-18.04
    steps:
      - run: REF="${GITHUB_REF:11}"
      - uses: octokit/request-action@v2.x
        with:
          route: POST /repos/{owner}/{repo}/actions/workflows/{workflow}/dispatches
          owner: gatsbyjs
          repo: gatsby-source-wordpress-experimental
          workflow: ci.yml
          ref: $REF
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
