name: Run Source Plugin PR CI for every WP Gatsby PR push
on: [push]
jobs:
  run_ci:
    runs-on: ubuntu-18.04
    steps:
      - run: echo "REF=${GITHUB_REF:11}" >> $GITHUB_ENV
      - run: echo $REF
      - uses: octokit/request-action@v2.x
        with:
          route: POST /repos/{owner}/{repo}/actions/workflows/{workflow}/dispatches
          owner: gatsbyjs
          repo: gatsby-source-wordpress-experimental
          workflow: ci.yml
          ref: ${{ env.REF }}
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
