name: Run Source Plugin PR CI for every WP Gatsby PR push
on:
  push:
    branches:
      - develop
      - master
jobs:
  create_pr:
    runs-on: ubuntu-18.04
    steps:
      - run: |
          curl --request POST \
            --url https://api.github.com/repos/gatsbyjs/gatsby-source-wordpress-experimental/actions/workflows/ci.yml/dispatches \
            --header 'Authorization: Bearer ${{ secrets.PAT }}' \
            --header 'Content-Type: application/json' \
            --data '{
            "ref": "$GITHUB_REF",
          }'
